# Generated by Django 4.2.5 on 2023-09-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookStoreModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Horror', 'Horror'), ('Thriller', 'Thriller'), ('Mystery', 'Mystery'), ('Humor', 'Humor'), ('Sci-Fi', 'Sci-Fi')], max_length=30)),
                ('first_pub', models.DateTimeField(auto_now_add=True)),
                ('last_pub', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
