# Generated by Django 4.2.5 on 2023-09-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstoremodel',
            name='category',
            field=models.CharField(choices=[('Horror', 'Horror'), ('Mystery', 'Mystery'), ('Sci-Fi', 'Sci-Fi'), ('Humor', 'Humor'), ('Thriller', 'Thriller')], max_length=30),
        ),
    ]
